/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacionsupletorio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author OrixStranger
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Connection conexion;
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtpanel = new javax.swing.JTextArea();
        btnClaveProducto = new javax.swing.JButton();
        btnpreciosArticulos = new javax.swing.JButton();
        precio250dolares = new javax.swing.JButton();
        btndescendeteprecio = new javax.swing.JButton();
        btnordenarNombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtpanel.setColumns(20);
        txtpanel.setRows(5);
        jScrollPane1.setViewportView(txtpanel);

        btnClaveProducto.setText("Obtener Clave de producto, nombre de producto y fabricante");
        btnClaveProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaveProductoActionPerformed(evt);
            }
        });

        btnpreciosArticulos.setText("Ordenar nombre y precio cuando el fabricante es Logintech alfabeticamente");
        btnpreciosArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreciosArticulosActionPerformed(evt);
            }
        });

        precio250dolares.setText("Ordenar por precio descendente");
        precio250dolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio250dolaresActionPerformed(evt);
            }
        });

        btndescendeteprecio.setText("Ordenar los datos del producto  descendente por precio");
        btndescendeteprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndescendeteprecioActionPerformed(evt);
            }
        });

        btnordenarNombre.setText("Ordenar por nombre ascendente");
        btnordenarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClaveProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpreciosArticulos)
                    .addComponent(precio250dolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnordenarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndescendeteprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnClaveProducto)
                        .addGap(43, 43, 43)
                        .addComponent(btnpreciosArticulos)
                        .addGap(47, 47, 47)
                        .addComponent(precio250dolares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnordenarNombre)
                        .addGap(19, 19, 19)
                        .addComponent(btndescendeteprecio)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClaveProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaveProductoActionPerformed
        // TODO add your handling code here:
        baseDatos();
        String cadena = "";
        try {
            Statement st = conexion.createStatement();
            ResultSet r = st.executeQuery("select * from articulo left join fabricante on articulo.clave_fabrica = fabricante.clave_fabricante");
            while(r.next()){
                String clave = r.getString("CLAVE_ART");
                String nombre = r.getString("NOMBRE");
                String clavef = r.getString(6);
                cadena = cadena +clave+" - "+ nombre + " - "+clavef+ "\n";//para q se presente en un cuadro de texto
            }
            txtpanel.setText(cadena);
            r.close();
            conexion.close();
        } catch (Exception e) {
        }
    }                                                     

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        baseDatos();
        String cadena = "";
        try {
            Statement st = conexion.createStatement();
            ResultSet r = st.executeQuery("select * from articulo");
            String sql = "";
            while(r.next()){
                String clave = r.getString("CLAVE_ART");
                String nombre = r.getString("NOMBRE");
                String clavef = r.getString("CLAVE_FABRICA");

                cadena = cadena +clave+" - "+ nombre + " - " +clavef+ "\n";//para q se presente en un cuadro de texto
            }
            txtpanel.setText(cadena);
            r.close();
            conexion.close();
        } catch (SQLException e) {
        }
        
    }//GEN-LAST:event_btnClaveProductoActionPerformed

    private void btnpreciosArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreciosArticulosActionPerformed
        // TODO add your handling code here:
        baseDatos();
        String cadena = "";
        try {
            Statement st = conexion.createStatement();
            ResultSet r = st.executeQuery("select * from articulo left join fabricante on articulo.clave_fabrica = fabricante.clave_fabricante where articulo.clave_fabrica = '3' order by articulo.nombre");
            String sql = "";
            while(r.next()){
                String clave = r.getString("nombre");
                String clavef = r.getString("precio");
                cadena = cadena +clave+" - "+ clavef + "\n";//para q se presente en un cuadro de texto
            }
            txtpanel.setText(cadena);
            r.close();
            conexion.close();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnpreciosArticulosActionPerformed

    private void precio250dolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio250dolaresActionPerformed
        // TODO add your handling code here:
        baseDatos();
        String cadena = "";
        try {
            Statement st = conexion.createStatement();
            ResultSet r = st.executeQuery("select * from articulo where precio > 250 order by precio DESC");
            String sql = "";
            while(r.next()){
                String clave = r.getString(2);
                String clavef = r.getString(3);
                cadena = cadena +clave+" - "+ clavef + "\n";//para q se presente en un cuadro de texto
            }
            txtpanel.setText(cadena);
            r.close();
            conexion.close();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_precio250dolaresActionPerformed

    private void btnordenarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarNombreActionPerformed
        // TODO add your handling code here:
        baseDatos();
        String cadena = "";
        try {
            Statement st = conexion.createStatement();
            ResultSet r = st.executeQuery("select * from articulo where precio > 250 order by nombre ASC");
            String sql = "";
            while(r.next()){
                
                String clave = r.getString(2);
                String clavef = r.getString(3);
                cadena = cadena +clave+" - "+ clavef + "\n";//para q se presente en un cuadro de texto
            }
            txtpanel.setText(cadena);
            r.close();
            conexion.close();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnordenarNombreActionPerformed

    private void btndescendeteprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndescendeteprecioActionPerformed
        // TODO add your handling code here:
        baseDatos();
        String cadena = "";
        try {
            Statement st = conexion.createStatement();
            ResultSet r = st.executeQuery("select * from articulo order by precio DESC");
            String sql = "";
            while(r.next()){
                String clave1  = r.getString(1);
                String clave = r.getString(2);
                String clavef = r.getString(3);
                String claveg = r.getString(4);
                cadena = cadena +clave1 + " - " + clave+" - "+ clavef + " - "+claveg + "\n";//para q se presente en un cuadro de texto
            }
            txtpanel.setText(cadena);
            r.close();
            conexion.close();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btndescendeteprecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    public void baseDatos() {

        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            System.out.println("Driver cargado !!!");
        } catch (ClassNotFoundException cnfe) {
            System.out.println("Error al cargar Driver " + cnfe);
        }

        try {
            String urlbd = "jdbc:derby://localhost:1527/tienda";
            conexion = DriverManager.getConnection(urlbd);
            System.out.println("Conexion satisfactoria !!!");
        } catch (SQLException sqlex) {
            System.out.println("Error al establecer conexion a la BD: " + sqlex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaveProducto;
    private javax.swing.JButton btndescendeteprecio;
    private javax.swing.JButton btnordenarNombre;
    private javax.swing.JButton btnpreciosArticulos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton precio250dolares;
    private javax.swing.JTextArea txtpanel;
    // End of variables declaration//GEN-END:variables
}
